apiVersion: v1
kind: Pod
metadata:
  name: kube-master
spec:
  hostNetwork: true
  volumes:
    - name: "etc-kubernetes"
      hostPath:
        path: "/etc/kubernetes"
    - name: "var-run-kubernetes"
      hostPath:
        path: "/var/run/kubernetes"
  containers:
    - name: "apiserver"
      image: "gcr.io/google_containers/hyperkube:v1.1.7"
      command: [ "/hyperkube", "apiserver" ]
      args:
        - "--allow-privileged=true"
        - "--etcd-servers=http://127.0.0.1:2379"
        - "--insecure-bind-address=0.0.0.0"
        - "--service-cluster-ip-range=__IP_RANGE__"
        - "--v=2"
      volumeMounts:
        - mountPath: /etc/kubernetes
          name: "etc-kubernetes"
        - mountPath: /var/run/kubernetes
          name: "var-run-kubernetes"
    - name: "controller"
      image: "gcr.io/google_containers/hyperkube:v1.1.7"
      command: [ "/hyperkube", "controller-manager" ]
      args:
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
    - name: "scheduler"
      image: "gcr.io/google_containers/hyperkube:v1.1.7"
      command: [ "/hyperkube", "scheduler" ]
      args:
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
